production:
  bucket: mcalpine
  access_key_id: AKIAJ4KOQTFLR6NPHO7Q
  secret_access_key: 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
development:
  bucket: mcalpine
  access_key_id: AKIAJ4KOQTFLR6NPHO7Q
  secret_access_key: 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